name: Open/Update PR to main on sandbox pushes

on:
  push:
    branches:
      - 'people/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create or update a PR from the current branch (people/*) -> main, using the GitHub API
      - name: Create or update PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = `${owner}:${context.ref.replace('refs/heads/','')}`;
            const base = 'main';

            // Try to find an existing open PR from this branch to main
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'open', head, base, per_page: 100
            });

            let prNumber;
            if (prs.data.length > 0) {
              prNumber = prs.data[0].number;
              core.info(`Found existing PR #${prNumber} for ${head} -> ${base}.`);
            } else {
              const title = `Sandbox: ${head.split(':')[1]}`;
              const body = 'Auto PR from sandbox branch (Theme Editor saves).';
              const created = await github.rest.pulls.create({ owner, repo, head, base, title, body, draft: false });
              prNumber = created.data.number;
              core.info(`Created PR #${prNumber} for ${head} -> ${base}.`);
            }

            core.setOutput('pr', prNumber);
