name: Auto PR and Auto-merge (people/* -> main)

on:
  push:
    branches:
      - 'people/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  open-update-and-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure GH CLI auth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status || echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: Create or update PR to main
        id: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If a PR from this branch to main exists, capture its number; else create one
          if gh pr view --base main --head "${GITHUB_REF_NAME}" >/dev/null 2>&1; then
            num=$(gh pr view --base main --head "${GITHUB_REF_NAME}" --json number -q .number)
          else
            gh pr create --base main --head "${GITHUB_REF_NAME}" \
              --title "Sandbox: ${GITHUB_REF_NAME}" \
              --body "Auto PR for ${GITHUB_REF_NAME} (Theme editor saves)."
            num=$(gh pr view --base main --head "${GITHUB_REF_NAME}" --json number -q .number)
          fi
          echo "number=$num" >> $GITHUB_OUTPUT

      - name: Enable auto-merge (squash) if possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash ${{ steps.pr.outputs.number }} || true
