name: Update last_update.txt on main merges

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # allows manual run from the Actions tab

permissions:
  contents: write

jobs:
  update-last:
    # prevent infinite loop when this job's own commit pushes to main
    if: ${{ !contains(github.event.head_commit.message, '[last-update-bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build message and write file
        run: |
          set -e
          TS="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
          # Use the commit SUBJECT only (no body / trailers), avoids newlines & "Co-authored-by"
          TITLE="$(git log -1 --pretty=%s)"
          SHA="$(git rev-parse --short HEAD)"
          mkdir -p assets
          printf '%s — %s (%s)\n' "$TS" "$TITLE" "$SHA" > assets/last_update.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add assets/last_update.txt
          # If the file didn't change, don't fail the workflow
          git commit -m "[last-update-bot] update last_update.txt" || exit 0
          git push