name: Update last_update.txt on main merges

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-last:
    # prevent infinite loop when this job's own commit pushes to main
    if: ${{ !contains(github.event.head_commit.message, '[last-update-bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build last update message
        id: meta
        run: |
          TS="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
          TITLE="${{ github.event.head_commit.message }}"
          SHA="${{ github.sha }}"
          echo "msg=${TS} — ${TITLE} (${SHA::7})" >> $GITHUB_OUTPUT

      - name: Write assets/last_update.txt
        run: |
          mkdir -p assets
          echo "${{ steps.meta.outputs.msg }}" > assets/last_update.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add assets/last_update.txt
          git commit -m "[last-update-bot] update last_update.txt"
          git push
